decide-update-4-1/decide-update-4.1

decide/booth/templates/booth/booth.html

Se modifica la forma de declarar componentes a la nueva versión.

research: Migración Vue.js  #11

---

decide/visualizer/templates/visualizer/visualizer.html

Se actualiza la vista de booth para funcionarl con la versión 3 de Vue.js

refactor: Adaptación vista

---

decide/booth/templates/booth/booth.html

Editada la vista de booth usando bootstrap 5 usando vue 3

research: Cambiada librería bootstrap-vue por bootstrap 5 #11

---

decide/booth/templates/booth/booth.html

Se han incluido la alerta de logueo. Login y votación no funcionales.

research: Incluida votación en booth #11

---

decide/store/views.py

Esta comprobación hace que el test de test_gen_vote_invalid sea correcto. Bug: Se ha comprobado que en el booth tiene bug que siempre accede a la votación más antigua creada.

research: Añadida comprobación en views.py de store #18

---

decide/base/mods.py
decide/booth/views.py
decide/store/views.py
decide/visualizer/views.py
decide/voting/urls.py
decide/voting/views.py

Se soluciona  error al filtrar el voting por el id pasado por url #20

fix: Error filtar voting

---

.github/workflows/django.yml

Se configura github actions al hacer push sobre la rama de develp #24

conf: Github Actions develop

---

.github/workflows/django.yml

Se sube la versión del postgres por error en integración continua

conf: Subida versión postgres

---

decide/booth/templates/booth/booth.html

Para la vista de booth, se ha añadido modal de registro y se han modificado las condiciones generales de botones de login y logout dentro del navbar, así como una reestructuración general del cuerpo.

feat: Añadido modal, modificado navbar y cambiada estructura general de booth

---

decide/booth/templates/booth/booth.html

Se ha cambiado las condiciones del título de la votación, ahora solo la muestra si el usuario se ha logueado. Añadida alerta de usuario para informar que se debe loguear.

feat: Cambios estructura votación y alerta

---

decide/base/mods.py
decide/booth/views.py
decide/store/views.py
decide/visualizer/views.py

Se modifica el filtrado de tablas a la nueva versión Django 4.1 #38

fix: Filtrado de tablas

---

.github/workflows/django.yml

Se añaden al workflow las versiones 3.8 y 3.9 de python #42

conf: workflow versiones python

---

.github/workflows/django.yml

Se actualizan las versiones para usar Node.js 16 en el workflow #42

conf: Actualización versiones

---

docker/Dockerfile
docker/docker-compose.yml
docker/docker-settings.py

Se actualizan las versiones de postgres y python. Se apunta a nuestro repositorio

conf: Configurado docker #49

---

README.md

Se han añadido las pautas necesarias para cargar datos iniciales a nuestro proyecto, así como la fuente sobre la que nos hemos basado para ello.

docs: añadidas en Readme.md carga inicial de datos  #32

---

README.md

Se ha añadido información sobre las credenciales de los usuarios creados en el populate.json y los tipos de votaciones.

docs: ampliada información README.md carga inicial datos #32

---

README.md

Corregido el número de usuarios definidos en la carga inicial de datos.

fix: corregido README.md carga inicial de datos #32

---

README.md

doc: añadido diario de equipo en carpeta doc #33

---

decide/booth/templates/booth/booth.html

Se ha modificado para que cuando se haga la accion correctamente se elimine la ventana de error

Fix: Modificado para eliminacion automatica de ventanas de error #56

---

decide/booth/templates/booth/booth.html
doc/diario-de-equipo.md

Merge de los cambios de mi rama

Workbranch manalerod2

---

docker/docker-settings.py

Se añade el host de docker a los orígenes confiables

conf: Configurado url docker #51

---

doc/diario-de-equipo.md

docs: Actualizado el diario de equipo #33

---

decide/booth/templates/booth/booth.html

fix: corregido mensaje de confirmación en el booth #31

---

README.md

docs: añadida guia rapida en README #32

---

doc/diario-de-equipo.md

docs: actualizacion diario #33

---

README.md

docs: actualizacion con test readme #32

---

README.md

docs: pequeña correción en el readme #32

---

.github/workflows/django.yml

Se elimina una funcionalidad en desarrollo

conf: Limpiando workflow
